// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sablou_Web.Models;

public partial class Bruger
{
    public int Id { get; set; }

    public string Navn { get; set; }

    public string Email { get; set; }

    public string Adresse { get; set; }

    public int? TelefonNummer { get; set; }

    public string Password { get; set; }

    public string Rolle { get; set; }
}