// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sablou_Web.Models;

[Table("ChokoladerIKatalog")]
public partial class ChokoladerIkatalog
{
    [Key]
    public int Id { get; set; }

    public int KatalogId { get; set; }

    public int ChokoladeId { get; set; }

    [ForeignKey("ChokoladeId")]
    [InverseProperty("ChokoladerIkatalog")]
    public virtual Chokolade Chokolade { get; set; }

    [ForeignKey("KatalogId")]
    [InverseProperty("ChokoladerIkatalog")]
    public virtual HøjtidsKatalog Katalog { get; set; }
}