// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sablou_Web.Models;

public partial class Chokolade
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    [Required]
    [StringLength(30)]
    public string Navn { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal Stykpris { get; set; }

    [Required]
    [StringLength(200)]
    public string Beskrivelse { get; set; }

    public int Antal { get; set; }

    [InverseProperty("Chokolade")]
    public virtual ICollection<ChokoladerIkatalog> ChokoladerIkatalog { get; set; } = new List<ChokoladerIkatalog>();

    [InverseProperty("Chokolade")]
    public virtual ICollection<IngrediensListe> IngrediensListe { get; set; } = new List<IngrediensListe>();
}