// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sablou_Web.Models;

public partial class Chokolade : IHarId
{
    public int Id { get; set; }

    public string Navn { get; set; }

    public decimal Stykpris { get; set; }

    public string Beskrivelse { get; set; }

    public virtual ICollection<Ingrediens> Ingrediens { get; set; } = new List<Ingrediens>();

    public virtual ICollection<HøjtidsKatalog> Katalog { get; set; } = new List<HøjtidsKatalog>();
}