// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Sablou_Web.Models;

public partial class cralle_dk_db_sablouContext : DbContext
{
    public cralle_dk_db_sablouContext()
    {
    }


    public cralle_dk_db_sablouContext(DbContextOptions<cralle_dk_db_sablouContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Bruger> Bruger { get; set; }

    public virtual DbSet<Chokolade> Chokolade { get; set; }

    public virtual DbSet<Højtider> Højtider { get; set; }

    public virtual DbSet<HøjtidsKatalog> HøjtidsKatalog { get; set; }

    public virtual DbSet<Ingrediens> Ingrediens { get; set; }

    public virtual DbSet<Ordre> Ordre { get; set; }

    public virtual DbSet<OrdreLinje> OrdreLinje { get; set; }

    public virtual DbSet<Rolle> Rolle { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Bruger>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Bruger__3214EC0766664BE7");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Adresse)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Navn)
                .IsRequired()
                .HasMaxLength(50);

            entity.HasOne(d => d.RolleType).WithMany(p => p.Bruger)
                .HasForeignKey(d => d.RolleTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_RolleTypeId");
        });

        modelBuilder.Entity<Chokolade>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Chokolad__3214EC07380F5FC6");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Beskrivelse)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.Navn)
                .IsRequired()
                .HasMaxLength(30);
            entity.Property(e => e.Stykpris).HasColumnType("decimal(18, 0)");

            entity.HasMany(d => d.Ingrediens).WithMany(p => p.Chokolade)
                .UsingEntity<Dictionary<string, object>>(
                    "IngrediensListe",
                    r => r.HasOne<Ingrediens>().WithMany()
                        .HasForeignKey("IngrediensId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK_IngrediensId"),
                    l => l.HasOne<Chokolade>().WithMany()
                        .HasForeignKey("ChokoladeId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK_ChokoladeId"),
                    j =>
                    {
                        j.HasKey("ChokoladeId", "IngrediensId").HasName("PK__Ingredie__235DDE11B1EE0E25");
                    });
        });

        modelBuilder.Entity<Højtider>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Højtider__3214EC0747CBE7BD");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Navn)
                .IsRequired()
                .HasMaxLength(20)
                .IsFixedLength();
        });

        modelBuilder.Entity<HøjtidsKatalog>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__HøjtidsK__3214EC0763394428");

            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.HasOne(d => d.Højt).WithMany(p => p.HøjtidsKatalog)
                .HasForeignKey(d => d.Højtid)
                .HasConstraintName("FK_Højtid");

            entity.HasMany(d => d.Chokolade).WithMany(p => p.Katalog)
                .UsingEntity<Dictionary<string, object>>(
                    "ChokoladerIkatalog",
                    r => r.HasOne<Chokolade>().WithMany()
                        .HasForeignKey("ChokoladeId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK_ChokoladeIKatalogId"),
                    l => l.HasOne<HøjtidsKatalog>().WithMany()
                        .HasForeignKey("KatalogId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK_KatalogId"),
                    j =>
                    {
                        j.HasKey("KatalogId", "ChokoladeId").HasName("PK__Chokolad__E4FC4A7D22D9A245");
                        j.ToTable("ChokoladerIKatalog");
                    });
        });

        modelBuilder.Entity<Ingrediens>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Ingredie__3214EC07170B0047");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Beskrivelse).HasMaxLength(100);
            entity.Property(e => e.Navn)
                .IsRequired()
                .HasMaxLength(30);
        });

        modelBuilder.Entity<Ordre>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Ordre__3214EC078C58FAB4");

            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.HasOne(d => d.Bruger).WithMany(p => p.Ordre)
                .HasForeignKey(d => d.BrugerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_BrugerId");
        });

        modelBuilder.Entity<OrdreLinje>(entity =>
        {
            entity.HasKey(e => new { e.ChokoladeId, e.OrdreId }).HasName("PK__OrdreLin__58E4A1147A4D30C3");

            entity.HasOne(d => d.Ordre).WithMany(p => p.OrdreLinje)
                .HasForeignKey(d => d.OrdreId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OrdreId");
        });

        modelBuilder.Entity<Rolle>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Rolle__3214EC078C933C78");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Rolletype).HasMaxLength(20);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}