// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Sablou_Web.Models;

public partial class cralle_dk_db_sablouContext : DbContext
{
    public cralle_dk_db_sablouContext()
    {
    }

    public cralle_dk_db_sablouContext(DbContextOptions<cralle_dk_db_sablouContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Bruger> Bruger { get; set; }

    public virtual DbSet<Chokolade> Chokolade { get; set; }

    public virtual DbSet<ChokoladerIkatalog> ChokoladerIkatalog { get; set; }

    public virtual DbSet<Højtider> Højtider { get; set; }

    public virtual DbSet<HøjtidsKatalog> HøjtidsKatalog { get; set; }

    public virtual DbSet<Ingrediens> Ingrediens { get; set; }

    public virtual DbSet<IngrediensListe> IngrediensListe { get; set; }

    public virtual DbSet<Kurv> Kurv { get; set; }

    public virtual DbSet<KurvLinje> KurvLinje { get; set; }

    public virtual DbSet<Ordre> Ordre { get; set; }

    public virtual DbSet<OrdreLinje> OrdreLinje { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=mssql13.unoeuro.com;Initial Catalog=cralle_dk_db_sablou;Persist Security Info=True;User ID=cralle_dk;Password=mDz296f5FegxdnrhG3EA;Encrypt=True");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Bruger>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Bruger__3214EC0720F9716B");

            entity.Property(e => e.Id).ValueGeneratedNever();
        });

        modelBuilder.Entity<Chokolade>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Chokolad__3214EC27DCC779E2");

            entity.Property(e => e.Id).ValueGeneratedNever();
        });

        modelBuilder.Entity<ChokoladerIkatalog>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tmp_ms_x__3214EC0745D9D771");

            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.HasOne(d => d.Chokolade).WithMany(p => p.ChokoladerIkatalog)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ChokoladeIKatalogId");

            entity.HasOne(d => d.Katalog).WithMany(p => p.ChokoladerIkatalog)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_KatalogId");
        });

        modelBuilder.Entity<Højtider>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Højtider__3214EC0747CBE7BD");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Navn).IsFixedLength();
        });

        modelBuilder.Entity<HøjtidsKatalog>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__HøjtidsK__3214EC0763394428");

            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.HasOne(d => d.Højt).WithMany(p => p.HøjtidsKatalog).HasConstraintName("FK_Højtid");
        });

        modelBuilder.Entity<Ingrediens>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Ingredie__3214EC07170B0047");

            entity.Property(e => e.Id).ValueGeneratedNever();
        });

        modelBuilder.Entity<IngrediensListe>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tmp_ms_x__3214EC071FAA53D9");

            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.HasOne(d => d.Chokolade).WithMany(p => p.IngrediensListe)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ChokoladeId");

            entity.HasOne(d => d.Ingrediens).WithMany(p => p.IngrediensListe)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_IngrediensId");
        });

        modelBuilder.Entity<Kurv>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Kurv__3214EC27D3868A9A");

            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.HasOne(d => d.Bruger).WithMany(p => p.Kurv).HasConstraintName("FK_Kurv_Bruger");
        });

        modelBuilder.Entity<KurvLinje>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__KurvLinj__3214EC27F6D8990F");

            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.HasOne(d => d.Kurv).WithMany(p => p.KurvLinje)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_KurvLinje_Kurv");
        });

        modelBuilder.Entity<Ordre>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Ordre__3214EC078C58FAB4");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Adresse).HasDefaultValue("");
            entity.Property(e => e.Dato).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.Email).HasDefaultValue("");
            entity.Property(e => e.Navn).HasDefaultValue("");
        });

        modelBuilder.Entity<OrdreLinje>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__OrdreLin__3214EC273E3F5A95");

            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.HasOne(d => d.Ordre).WithMany(p => p.OrdreLinje)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_OrdreLinje_Ordre");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}