// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Sablou_Web.Models;

public partial class cralle_dk_db_sablouContext : DbContext
{
    public cralle_dk_db_sablouContext()
    {
    }

    public cralle_dk_db_sablouContext(DbContextOptions<cralle_dk_db_sablouContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Bruger> Bruger { get; set; }

    public virtual DbSet<Chokolade> Chokolade { get; set; }

    public virtual DbSet<Højtider> Højtider { get; set; }

    public virtual DbSet<HøjtidsKatalog> HøjtidsKatalog { get; set; }

    public virtual DbSet<Ingrediens> Ingrediens { get; set; }

    public virtual DbSet<IngrediensListe> IngrediensListe { get; set; }

    public virtual DbSet<Ordre> Ordre { get; set; }

    public virtual DbSet<OrdreLinje> OrdreLinje { get; set; }

    public virtual DbSet<Test> Test { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=mssql13.unoeuro.com;Initial Catalog=cralle_dk_db_sablou;Persist Security Info=True;User ID=cralle_dk;Password=mDz296f5FegxdnrhG3EA;Encrypt=True");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Bruger>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Bruger__3214EC0720F9716B");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Adresse)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Navn)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Password)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.Rolle)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<Chokolade>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Chokolad__3214EC07380F5FC6");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Beskrivelse)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.Navn)
                .IsRequired()
                .HasMaxLength(30);
            entity.Property(e => e.Stykpris).HasColumnType("decimal(18, 0)");
        });

        modelBuilder.Entity<Højtider>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Højtider__3214EC0747CBE7BD");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Navn)
                .IsRequired()
                .HasMaxLength(20)
                .IsFixedLength();
        });

        modelBuilder.Entity<HøjtidsKatalog>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__HøjtidsK__3214EC0763394428");

            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.HasOne(d => d.Højt).WithMany(p => p.HøjtidsKatalog)
                .HasForeignKey(d => d.Højtid)
                .HasConstraintName("FK_Højtid");

            entity.HasMany(d => d.Chokolade).WithMany(p => p.Katalog)
                .UsingEntity<Dictionary<string, object>>(
                    "ChokoladerIkatalog",
                    r => r.HasOne<Chokolade>().WithMany()
                        .HasForeignKey("ChokoladeId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK_ChokoladeIKatalogId"),
                    l => l.HasOne<HøjtidsKatalog>().WithMany()
                        .HasForeignKey("KatalogId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK_KatalogId"),
                    j =>
                    {
                        j.HasKey("KatalogId", "ChokoladeId").HasName("PK__Chokolad__E4FC4A7D22D9A245");
                        j.ToTable("ChokoladerIKatalog");
                    });
        });

        modelBuilder.Entity<Ingrediens>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Ingredie__3214EC07170B0047");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Beskrivelse).HasMaxLength(100);
            entity.Property(e => e.Navn)
                .IsRequired()
                .HasMaxLength(30);
        });

        modelBuilder.Entity<IngrediensListe>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tmp_ms_x__3214EC071FAA53D9");

            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.HasOne(d => d.Chokolade).WithMany(p => p.IngrediensListe)
                .HasForeignKey(d => d.ChokoladeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ChokoladeId");

            entity.HasOne(d => d.Ingrediens).WithMany(p => p.IngrediensListe)
                .HasForeignKey(d => d.IngrediensId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_IngrediensId");
        });

        modelBuilder.Entity<Ordre>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Ordre__3214EC078C58FAB4");

            entity.Property(e => e.Id).ValueGeneratedNever();
        });

        modelBuilder.Entity<OrdreLinje>(entity =>
        {
            entity.HasKey(e => new { e.ChokoladeId, e.OrdreId }).HasName("PK__OrdreLin__58E4A1147A4D30C3");

            entity.HasOne(d => d.Ordre).WithMany(p => p.OrdreLinje)
                .HasForeignKey(d => d.OrdreId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OrdreId");
        });

        modelBuilder.Entity<Test>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Test__3214EC0794B0D4AF");

            entity.Property(e => e.Id).ValueGeneratedNever();
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}