// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sablou_Web.Models;

public partial class Højtider
{
    public int Id { get; set; }

    public string Navn { get; set; }

    public virtual ICollection<HøjtidsKatalog> HøjtidsKatalog { get; set; } = new List<HøjtidsKatalog>();
}