// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sablou_Web.Models;

public partial class HøjtidsKatalog
{
    public int Id { get; set; }

    public int? Højtid { get; set; }

    public virtual Højtider Højt { get; set; }

    public virtual ICollection<Chokolade> Chokolade { get; set; } = new List<Chokolade>();
}