// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sablou_Web.Models;

public partial class Ingrediens
{
    public int Id { get; set; }

    public string Navn { get; set; }

    public string Beskrivelse { get; set; }

    public virtual ICollection<Chokolade> Chokolade { get; set; } = new List<Chokolade>();
}