// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sablou_Web.Models;

public partial class IngrediensListe
{
    public int Id { get; set; }

    public int ChokoladeId { get; set; }

    public int IngrediensId { get; set; }

    public virtual Chokolade Chokolade { get; set; }

    public virtual Ingrediens Ingrediens { get; set; }
}