// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sablou_Web.Models;

public partial class IngrediensListe
{
    [Key]
    public int Id { get; set; }

    public int ChokoladeId { get; set; }

    public int IngrediensId { get; set; }

    [ForeignKey("ChokoladeId")]
    [InverseProperty("IngrediensListe")]
    public virtual Chokolade Chokolade { get; set; }

    [ForeignKey("IngrediensId")]
    [InverseProperty("IngrediensListe")]
    public virtual Ingrediens Ingrediens { get; set; }
}