// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sablou_Web.Models;

public partial class Kurv
{
    [Key]
    public int Id { get; set; }

    [Column("BrugerID")]
    public int BrugerId { get; set; }

    [ForeignKey("BrugerId")]
    [InverseProperty("Kurv")]
    public virtual Bruger Bruger { get; set; }

    [InverseProperty("Kurv")]
    public virtual ICollection<KurvLinje> KurvLinje { get; set; } = new List<KurvLinje>();
}