// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sablou_Web.Models;

public partial class Ordre
{
    public int Id { get; set; }

    public int BrugerId { get; set; }

    public virtual Bruger Bruger { get; set; }

    public virtual ICollection<OrdreLinje> OrdreLinje { get; set; } = new List<OrdreLinje>();
}