// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sablou_Web.Models;

public partial class Ordre
{
    [Key]
    public int Id { get; set; }

    public int? BrugerId { get; set; }

    [Required]
    [StringLength(100)]
    public string Navn { get; set; }

    [Required]
    [StringLength(100)]
    public string Email { get; set; }

    [StringLength(20)]
    public string Telefon { get; set; }

    [Required]
    [StringLength(200)]
    public string Adresse { get; set; }

    [StringLength(500)]
    public string Besked { get; set; }

    public bool ErLoggetInd { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Dato { get; set; }

    public bool Behandlet { get; set; }

    public bool ErAnnulleret { get; set; }

    [InverseProperty("Ordre")]
    public virtual ICollection<OrdreLinje> OrdreLinje { get; set; } = new List<OrdreLinje>();
}