// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sablou_Web.Models;

public partial class OrdreLinje
{
    public int ChokoladeId { get; set; }

    public int OrdreId { get; set; }

    public int? Antal { get; set; }

    public virtual Ordre Ordre { get; set; }
}