// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sablou_Web.Models;

public partial class OrdreLinje
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    [Column("OrdreID")]
    public int? OrdreId { get; set; }

    [Column("ChokoladeID")]
    public int ChokoladeId { get; set; }

    public int Antal { get; set; }

    [ForeignKey("OrdreId")]
    [InverseProperty("OrdreLinje")]
    public virtual Ordre Ordre { get; set; }
}