// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sablou_Web.Models;

public partial class Rolle
{
    public int Id { get; set; }

    public string Rolletype { get; set; }

    public virtual ICollection<Bruger> Bruger { get; set; } = new List<Bruger>();
}